# Generated by Django 5.2 on 2025-05-03 21:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='Наименование типа')),
                ('mask_sn', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[NAaXZ]+$')], verbose_name='Маска серийного номера')),
            ],
            options={
                'verbose_name': 'Тип оборубования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype', verbose_name='Код типа оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
                'unique_together': {('equipment_type', 'serial_number')},
            },
        ),
    ]
