# Generated by Django 5.2 on 2025-05-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
        migrations.AlterModelTable(
            name='equipmenttype',
            table='equipment_type',
        ),
    ]
